site_name: Project Chameleon
docs_dir: src
site_dir: ../docs

nav:
  - Top page: 'index.md'
  - 'Discovering a new relocation entry of ARM64X in recent Windows 10 on Arm': 'new_reloc_chpev2.md'

repo_url: https://github.com/FFRI/ProjectChameleon
edit_uri: edit/main/docs_src/src/

theme:
  name: material

markdown_extensions:
  - codehilite
  - footnotes
  - attr_list
  - toc:
      permalink: true
  - pymdownx.magiclink
